name: Build and Publish Docker Image

on:
  push:
    branches:
      - master # Cambia esto al nombre de la rama en la que deseas activar la acción

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sebastiansam/pruebadocker:latest .
        working-directory: .

      - name: Push Docker image
        run: docker push sebastiansam/pruebadocker:latest
